name: Dev
on:
  pull_request:
    branches:
      - main
      - refactor

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: ESLint
        run: yarn test:ci

  format:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn prettier
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: apply formatting changes
          branch: ${{ github.head_ref }}
